### PR TITLE
Support for optional count number

### PR DESCRIPTION
**Pull request by pchampio**
A number may precede `<Plug>(edgemotion-j`) to multiply the command

### CODE REVIEW

**Comment by pchampio** [comment]
Edgemotion calculates a number (5 for example) of lines to jump.
`<Plug>(edgemotion-j)` can translate to `:normal 5j`
[Calculation code](https://github.com/haya14busa/vim-edgemotion/blob/8d16bd92f6203dfe44157d43be7880f34fd5c060/autoload/edgemotion.vim#L55)

If the user type `2 <Plug>(edgemotion-j)` the expected behavior is to execute the command twice. Equivalent to `<Plug>(edgemotion-j)`  + `<Plug>(edgemotion-j)` 

But what is happening is `:normal 25j` the preceded 2 is concatenated to the calculated 5, resulting in a miss behavior.

**Comment by pchampio** [comment]
I tried to update the test, but failed.

When using the 'x' flags in the `feedkeys` function the tests are green.
However the 'x' flags breaks the functionality with custom operation (`operatorfunc`)

**Comment by Drakirus** [comment]
Note the use of the flag 'x' breaks the plugin when using custom `'operatorfunc'`.

**Comment by pchampio** [comment]
Closing this PR as my fork as diverged quite a bit.

**Pull request closed without merging**
